name: coverage

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          pattern: coverage_*.xml
          path: coverage/
          github-token: ${{ secrets.GH_WORKFLOW_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
          override_commit: ${{ github.event.workflow_run.head_commit.id }}
